# Importa todos los modelos para que SQLAlchemy los registre
from app.core.database import Base
from .backups import Backups
from .categoria_padre import CategoriaPadre
from .clientes import Clientes
from .configuracion import Configuracion
from .conductores import Conductores
from .empleados import Empleados
from .marcas import Marcas
from .permisos import Permisos
from .proveedores import Proveedores
from .restauraciones import Restauraciones
from .roles import Roles
from .ruta import Ruta
from .tipo_vehiculo import TipoVehiculo
from .tipos_almacen import TiposAlmacen
from .unidades_medida import UnidadesMedida
from .almacenes import Almacenes
from .auditoria import Auditoria
from .categorias import Categorias
from .empleado_rol import EmpleadoRol
from .movimiento import Movimiento
from .proveedor_contacto import ProveedorContacto
from .rol_permiso import RolPermiso
from .vehiculo import Vehiculo
from .compras import Compras
from .mantenimiento_vehiculo import MantenimientoVehiculo
from .pedidos_clientes import PedidosClientes
from .pedidos_proveedores import PedidosProveedores
from .productos import Productos
from .traslados_internos import TrasladosInternos
from .compra_detalle import CompraDetalle
from .devoluciones_clientes import DevolucionesClientes
from .devoluciones_proveedores import DevolucionesProveedores
from .envios import Envios
from .guia_remision import GuiaRemision
from .movimiento_detalle import MovimientoDetalle
from .pedido_cliente_detalle import PedidoClienteDetalle
from .pedido_proveedor_detalle import PedidoProveedorDetalle
from .productos_almacen import ProductosAlmacen
from .traslado_interno_detalle import TrasladoInternoDetalle
from .asignacion_transporte import AsignacionTransporte
from .devolucion_cliente_detalle import DevolucionClienteDetalle
from .devolucion_proveedor_detalle import DevolucionProveedorDetalle
from .envio_detalle import EnvioDetalle
from .guia_remision_detalle import GuiaRemisionDetalle
from .ruta_envio import RutaEnvio
from .seguimiento_envio import SeguimientoEnvio