"""Add all tables from models

Revision ID: b30940f0877b
Revises: 03c709b3238f
Create Date: 2026-04-27 16:28:15.394335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b30940f0877b'
down_revision: Union[str, None] = '03c709b3238f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('id_backup', sa.Integer(), nullable=False),
    sa.Column('fecha_backup', sa.DateTime(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_backup')
    )
    op.create_table('configuracion',
    sa.Column('id_configuracion', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_configuracion')
    )
    op.create_index('clave', 'configuracion', ['clave'], unique=True)
    op.create_table('permisos',
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_permiso')
    )
    op.create_index('nombre', 'permisos', ['nombre'], unique=True)
    op.create_table('restauraciones',
    sa.Column('id_restauracion', sa.Integer(), nullable=False),
    sa.Column('fecha_restauracion', sa.DateTime(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_restauracion')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_index('nombre', 'roles', ['nombre'], unique=True)
    op.create_table('ruta',
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=100), nullable=False),
    sa.Column('destino', sa.String(length=100), nullable=False),
    sa.Column('distancia', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tiempo_estimado', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id_ruta')
    )
    op.create_table('auditoria',
    sa.Column('id_auditoria', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['empleados.id_empleado'], name='auditoria_ibfk_1'),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    op.create_index('idx_auditoria_fecha', 'auditoria', ['fecha'], unique=False)
    op.create_index('idx_auditoria_usuario', 'auditoria', ['id_usuario'], unique=False)
    op.create_table('conductores',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('licencia_conducir', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], name='conductores_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_empleado')
    )
    op.create_table('empleado_rol',
    sa.Column('id_empleado_rol', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], name='empleado_rol_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], name='empleado_rol_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_empleado_rol')
    )
    op.create_index('id_rol', 'empleado_rol', ['id_rol'], unique=False)
    op.create_index('uk_empleado_rol', 'empleado_rol', ['id_empleado', 'id_rol'], unique=True)
    op.create_table('movimiento',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=20), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['empleados.id_empleado'], name='movimiento_ibfk_1'),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_index('idx_movimiento_fecha', 'movimiento', ['fecha'], unique=False)
    op.create_index('idx_movimiento_usuario', 'movimiento', ['id_usuario'], unique=False)
    op.create_table('rol_permiso',
    sa.Column('id_rol_permiso', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['permisos.id_permiso'], name='rol_permiso_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], name='rol_permiso_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_rol_permiso')
    )
    op.create_index('id_permiso', 'rol_permiso', ['id_permiso'], unique=False)
    op.create_index('uk_rol_permiso', 'rol_permiso', ['id_rol', 'id_permiso'], unique=True)
    op.create_table('compras',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.Date(), server_default=sa.text('(curdate())'), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_almacen', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('estatus', sa.String(length=20), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=50), nullable=True),
    sa.Column('serie', sa.String(length=20), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.CheckConstraint('(`subtotal` >= 0)', name='compras_chk_1'),
    sa.ForeignKeyConstraint(['id_almacen'], ['almacenes.id_almacen'], name='compras_ibfk_2'),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], name='compras_ibfk_3'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='compras_ibfk_1'),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_index('idx_compra_almacen', 'compras', ['id_almacen'], unique=False)
    op.create_index('idx_compra_empleado', 'compras', ['id_empleado'], unique=False)
    op.create_index('idx_compra_proveedor', 'compras', ['id_proveedor'], unique=False)
    op.create_table('mantenimiento_vehiculo',
    sa.Column('id_mantenimiento', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('fecha_mantenimiento', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('costo', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id_vehiculo'], name='mantenimiento_vehiculo_ibfk_1'),
    sa.PrimaryKeyConstraint('id_mantenimiento')
    )
    op.create_index('id_vehiculo', 'mantenimiento_vehiculo', ['id_vehiculo'], unique=False)
    op.create_table('pedidos_clientes',
    sa.Column('id_pedido_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), server_default=sa.text('(curdate())'), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_almacen', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('impuesto', sa.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('estatus', sa.String(length=20), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('requiere_envio', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=True),
    sa.CheckConstraint('(`subtotal` >= 0)', name='pedidos_clientes_chk_1'),
    sa.CheckConstraint('(`total` >= 0)', name='pedidos_clientes_chk_2'),
    sa.ForeignKeyConstraint(['id_almacen'], ['almacenes.id_almacen'], name='pedidos_clientes_ibfk_3'),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name='pedidos_clientes_ibfk_1'),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], name='pedidos_clientes_ibfk_2'),
    sa.PrimaryKeyConstraint('id_pedido_cliente')
    )
    op.create_index('idx_pc_almacen', 'pedidos_clientes', ['id_almacen'], unique=False)
    op.create_index('idx_pc_cliente', 'pedidos_clientes', ['id_cliente'], unique=False)
    op.create_index('idx_pc_empleado', 'pedidos_clientes', ['id_empleado'], unique=False)
    op.create_table('pedidos_proveedores',
    sa.Column('id_pedido_proveedor', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), server_default=sa.text('(curdate())'), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_almacen', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('impuesto', sa.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('estatus', sa.String(length=20), server_default=sa.text("'pendiente'"), nullable=False),
    sa.ForeignKeyConstraint(['id_almacen'], ['almacenes.id_almacen'], name='pedidos_proveedores_ibfk_3'),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], name='pedidos_proveedores_ibfk_2'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='pedidos_proveedores_ibfk_1'),
    sa.PrimaryKeyConstraint('id_pedido_proveedor')
    )
    op.create_index('id_almacen', 'pedidos_proveedores', ['id_almacen'], unique=False)
    op.create_index('idx_pp_empleado', 'pedidos_proveedores', ['id_empleado'], unique=False)
    op.create_index('idx_pp_proveedor', 'pedidos_proveedores', ['id_proveedor'], unique=False)
    op.create_table('traslados_internos',
    sa.Column('id_traslado', sa.Integer(), nullable=False),
    sa.Column('fecha_traslado', sa.Date(), server_default=sa.text('(curdate())'), nullable=False),
    sa.Column('id_almacen_origen', sa.Integer(), nullable=False),
    sa.Column('id_almacen_destino', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.String(length=20), nullable=False),
    sa.CheckConstraint('(`id_almacen_origen` <> `id_almacen_destino`)', name='traslados_internos_chk_1'),
    sa.ForeignKeyConstraint(['id_almacen_destino'], ['almacenes.id_almacen'], name='traslados_internos_ibfk_2'),
    sa.ForeignKeyConstraint(['id_almacen_origen'], ['almacenes.id_almacen'], name='traslados_internos_ibfk_1'),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], name='traslados_internos_ibfk_3'),
    sa.PrimaryKeyConstraint('id_traslado')
    )
    op.create_index('id_almacen_destino', 'traslados_internos', ['id_almacen_destino'], unique=False)
    op.create_index('id_almacen_origen', 'traslados_internos', ['id_almacen_origen'], unique=False)
    op.create_index('id_empleado', 'traslados_internos', ['id_empleado'], unique=False)
    op.create_table('compra_detalle',
    sa.Column('id_compra_detalle', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('(`cantidad` > 0)', name='compra_detalle_chk_1'),
    sa.CheckConstraint('(`precio_unitario` >= 0)', name='compra_detalle_chk_2'),
    sa.CheckConstraint('(`subtotal` >= 0)', name='compra_detalle_chk_3'),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id_compra'], name='compra_detalle_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_movimiento'], ['movimiento.id_movimiento'], name='compra_detalle_ibfk_3'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='compra_detalle_ibfk_2'),
    sa.PrimaryKeyConstraint('id_compra_detalle')
    )
    op.create_index('idx_cd_compra', 'compra_detalle', ['id_compra'], unique=False)
    op.create_index('idx_cd_movimiento', 'compra_detalle', ['id_movimiento'], unique=False)
    op.create_index('idx_cd_producto', 'compra_detalle', ['id_producto'], unique=False)
    op.create_table('devoluciones_clientes',
    sa.Column('id_devolucion', sa.Integer(), nullable=False),
    sa.Column('id_pedido_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), server_default=sa.text('(curdate())'), nullable=False),
    sa.Column('estatus', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido_cliente'], ['pedidos_clientes.id_pedido_cliente'], name='devoluciones_clientes_ibfk_1'),
    sa.PrimaryKeyConstraint('id_devolucion')
    )
    op.create_index('id_pedido_cliente', 'devoluciones_clientes', ['id_pedido_cliente'], unique=False)
    op.create_table('devoluciones_proveedores',
    sa.Column('id_devolucion', sa.Integer(), nullable=False),
    sa.Column('id_pedido_proveedor', sa.Integer(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), server_default=sa.text('(curdate())'), nullable=False),
    sa.Column('estatus', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido_proveedor'], ['pedidos_proveedores.id_pedido_proveedor'], name='devoluciones_proveedores_ibfk_1'),
    sa.PrimaryKeyConstraint('id_devolucion')
    )
    op.create_index('id_pedido_proveedor', 'devoluciones_proveedores', ['id_pedido_proveedor'], unique=False)
    op.create_table('envios',
    sa.Column('id_envio', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.Date(), server_default=sa.text('(curdate())'), nullable=False),
    sa.Column('id_pedido_cliente', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.String(length=20), server_default=sa.text("'pendiente'"), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], name='envios_ibfk_3'),
    sa.ForeignKeyConstraint(['id_pedido_cliente'], ['pedidos_clientes.id_pedido_cliente'], name='envios_ibfk_1'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id_vehiculo'], name='envios_ibfk_2'),
    sa.PrimaryKeyConstraint('id_envio')
    )
    op.create_index('id_empleado', 'envios', ['id_empleado'], unique=False)
    op.create_index('idx_envio_vehiculo', 'envios', ['id_vehiculo'], unique=False)
    op.create_index('uk_envio_pedido', 'envios', ['id_pedido_cliente'], unique=True)
    op.create_table('guia_remision',
    sa.Column('id_guia', sa.Integer(), nullable=False),
    sa.Column('id_pedido_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha_guia', sa.Date(), server_default=sa.text('(curdate())'), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_conductor', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_conductor'], ['conductores.id_empleado'], name='guia_remision_ibfk_3'),
    sa.ForeignKeyConstraint(['id_pedido_cliente'], ['pedidos_clientes.id_pedido_cliente'], name='guia_remision_ibfk_1'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id_vehiculo'], name='guia_remision_ibfk_2'),
    sa.PrimaryKeyConstraint('id_guia')
    )
    op.create_index('id_pedido_cliente', 'guia_remision', ['id_pedido_cliente'], unique=False)
    op.create_index('idx_gr_conductor', 'guia_remision', ['id_conductor'], unique=False)
    op.create_index('idx_gr_vehiculo', 'guia_remision', ['id_vehiculo'], unique=False)
    op.create_table('movimiento_detalle',
    sa.Column('id_movimiento_detalle', sa.Integer(), nullable=False),
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_almacen', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_almacen'], ['almacenes.id_almacen'], name='movimiento_detalle_ibfk_3'),
    sa.ForeignKeyConstraint(['id_movimiento'], ['movimiento.id_movimiento'], name='movimiento_detalle_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='movimiento_detalle_ibfk_2'),
    sa.PrimaryKeyConstraint('id_movimiento_detalle')
    )
    op.create_index('idx_md_almacen', 'movimiento_detalle', ['id_almacen'], unique=False)
    op.create_index('idx_md_movimiento', 'movimiento_detalle', ['id_movimiento'], unique=False)
    op.create_index('idx_md_producto', 'movimiento_detalle', ['id_producto'], unique=False)
    op.create_table('pedido_cliente_detalle',
    sa.Column('id_pedido_cliente_detalle', sa.Integer(), nullable=False),
    sa.Column('id_pedido_cliente', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('(`cantidad` > 0)', name='pedido_cliente_detalle_chk_1'),
    sa.ForeignKeyConstraint(['id_pedido_cliente'], ['pedidos_clientes.id_pedido_cliente'], name='pedido_cliente_detalle_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='pedido_cliente_detalle_ibfk_2'),
    sa.PrimaryKeyConstraint('id_pedido_cliente_detalle')
    )
    op.create_index('idx_pcd_pedido', 'pedido_cliente_detalle', ['id_pedido_cliente'], unique=False)
    op.create_index('idx_pcd_producto', 'pedido_cliente_detalle', ['id_producto'], unique=False)
    op.create_table('pedido_proveedor_detalle',
    sa.Column('id_pedido_proveedor_detalle', sa.Integer(), nullable=False),
    sa.Column('id_pedido_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido_proveedor'], ['pedidos_proveedores.id_pedido_proveedor'], name='pedido_proveedor_detalle_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='pedido_proveedor_detalle_ibfk_2'),
    sa.PrimaryKeyConstraint('id_pedido_proveedor_detalle')
    )
    op.create_index('id_pedido_proveedor', 'pedido_proveedor_detalle', ['id_pedido_proveedor'], unique=False)
    op.create_index('id_producto', 'pedido_proveedor_detalle', ['id_producto'], unique=False)
    op.create_table('productos_almacen',
    sa.Column('id_producto_almacen', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_almacen', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('stock_maximo', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.CheckConstraint('(`stock` >= 0)', name='productos_almacen_chk_1'),
    sa.ForeignKeyConstraint(['id_almacen'], ['almacenes.id_almacen'], name='productos_almacen_ibfk_2'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='productos_almacen_ibfk_1'),
    sa.PrimaryKeyConstraint('id_producto_almacen')
    )
    op.create_index('idx_pa_almacen', 'productos_almacen', ['id_almacen'], unique=False)
    op.create_index('idx_pa_producto', 'productos_almacen', ['id_producto'], unique=False)
    op.create_index('uk_producto_almacen', 'productos_almacen', ['id_producto', 'id_almacen'], unique=True)
    op.create_table('traslado_interno_detalle',
    sa.Column('id_traslado_detalle', sa.Integer(), nullable=False),
    sa.Column('id_traslado', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='traslado_interno_detalle_ibfk_2'),
    sa.ForeignKeyConstraint(['id_traslado'], ['traslados_internos.id_traslado'], name='traslado_interno_detalle_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_traslado_detalle')
    )
    op.create_index('id_producto', 'traslado_interno_detalle', ['id_producto'], unique=False)
    op.create_index('id_traslado', 'traslado_interno_detalle', ['id_traslado'], unique=False)
    op.create_table('asignacion_transporte',
    sa.Column('id_asignacion', sa.Integer(), nullable=False),
    sa.Column('id_envio', sa.Integer(), nullable=False),
    sa.Column('id_conductor', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.Date(), server_default=sa.text('(curdate())'), nullable=False),
    sa.ForeignKeyConstraint(['id_conductor'], ['conductores.id_empleado'], name='asignacion_transporte_ibfk_2'),
    sa.ForeignKeyConstraint(['id_envio'], ['envios.id_envio'], name='asignacion_transporte_ibfk_1'),
    sa.PrimaryKeyConstraint('id_asignacion')
    )
    op.create_index('id_envio', 'asignacion_transporte', ['id_envio'], unique=False)
    op.create_index('idx_at_conductor', 'asignacion_transporte', ['id_conductor'], unique=False)
    op.create_table('devolucion_cliente_detalle',
    sa.Column('id_devolucion_detalle', sa.Integer(), nullable=False),
    sa.Column('id_devolucion', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_devolucion'], ['devoluciones_clientes.id_devolucion'], name='devolucion_cliente_detalle_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='devolucion_cliente_detalle_ibfk_2'),
    sa.PrimaryKeyConstraint('id_devolucion_detalle')
    )
    op.create_index('id_devolucion', 'devolucion_cliente_detalle', ['id_devolucion'], unique=False)
    op.create_index('id_producto', 'devolucion_cliente_detalle', ['id_producto'], unique=False)
    op.create_table('devolucion_proveedor_detalle',
    sa.Column('id_devolucion_detalle', sa.Integer(), nullable=False),
    sa.Column('id_devolucion', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_devolucion'], ['devoluciones_proveedores.id_devolucion'], name='devolucion_proveedor_detalle_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='devolucion_proveedor_detalle_ibfk_2'),
    sa.PrimaryKeyConstraint('id_devolucion_detalle')
    )
    op.create_index('id_devolucion', 'devolucion_proveedor_detalle', ['id_devolucion'], unique=False)
    op.create_index('id_producto', 'devolucion_proveedor_detalle', ['id_producto'], unique=False)
    op.create_table('envio_detalle',
    sa.Column('id_envio_detalle', sa.Integer(), nullable=False),
    sa.Column('id_envio', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_envio'], ['envios.id_envio'], name='envio_detalle_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='envio_detalle_ibfk_2'),
    sa.PrimaryKeyConstraint('id_envio_detalle')
    )
    op.create_index('id_envio', 'envio_detalle', ['id_envio'], unique=False)
    op.create_index('id_producto', 'envio_detalle', ['id_producto'], unique=False)
    op.create_table('guia_remision_detalle',
    sa.Column('id_guia_detalle', sa.Integer(), nullable=False),
    sa.Column('id_guia', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_guia'], ['guia_remision.id_guia'], name='guia_remision_detalle_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='guia_remision_detalle_ibfk_2'),
    sa.PrimaryKeyConstraint('id_guia_detalle')
    )
    op.create_index('id_guia', 'guia_remision_detalle', ['id_guia'], unique=False)
    op.create_index('id_producto', 'guia_remision_detalle', ['id_producto'], unique=False)
    op.create_table('ruta_envio',
    sa.Column('id_ruta_envio', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('id_envio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_envio'], ['envios.id_envio'], name='ruta_envio_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_ruta'], ['ruta.id_ruta'], name='ruta_envio_ibfk_1'),
    sa.PrimaryKeyConstraint('id_ruta_envio')
    )
    op.create_index('idx_re_envio', 'ruta_envio', ['id_envio'], unique=False)
    op.create_index('idx_re_ruta', 'ruta_envio', ['id_ruta'], unique=False)
    op.create_table('seguimiento_envio',
    sa.Column('id_seguimiento', sa.Integer(), nullable=False),
    sa.Column('id_envio', sa.Integer(), nullable=False),
    sa.Column('fecha_seguimiento', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('estatus', sa.String(length=20), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_envio'], ['envios.id_envio'], name='seguimiento_envio_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_seguimiento')
    )
    op.create_index('idx_se_envio', 'seguimiento_envio', ['id_envio'], unique=False)
    op.add_column('tipos_almacen', sa.Column('nombre', sa.String(length=50), nullable=False))
    op.drop_index('nombre_tipo', table_name='tipos_almacen')
    op.create_index('nombre', 'tipos_almacen', ['nombre'], unique=True)
    op.drop_column('tipos_almacen', 'nombre_tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_almacen', sa.Column('nombre_tipo', mysql.VARCHAR(length=50), nullable=False))
    op.drop_index('nombre', table_name='tipos_almacen')
    op.create_index('nombre_tipo', 'tipos_almacen', ['nombre_tipo'], unique=True)
    op.drop_column('tipos_almacen', 'nombre')
    op.drop_index('idx_se_envio', table_name='seguimiento_envio')
    op.drop_table('seguimiento_envio')
    op.drop_index('idx_re_ruta', table_name='ruta_envio')
    op.drop_index('idx_re_envio', table_name='ruta_envio')
    op.drop_table('ruta_envio')
    op.drop_index('id_producto', table_name='guia_remision_detalle')
    op.drop_index('id_guia', table_name='guia_remision_detalle')
    op.drop_table('guia_remision_detalle')
    op.drop_index('id_producto', table_name='envio_detalle')
    op.drop_index('id_envio', table_name='envio_detalle')
    op.drop_table('envio_detalle')
    op.drop_index('id_producto', table_name='devolucion_proveedor_detalle')
    op.drop_index('id_devolucion', table_name='devolucion_proveedor_detalle')
    op.drop_table('devolucion_proveedor_detalle')
    op.drop_index('id_producto', table_name='devolucion_cliente_detalle')
    op.drop_index('id_devolucion', table_name='devolucion_cliente_detalle')
    op.drop_table('devolucion_cliente_detalle')
    op.drop_index('idx_at_conductor', table_name='asignacion_transporte')
    op.drop_index('id_envio', table_name='asignacion_transporte')
    op.drop_table('asignacion_transporte')
    op.drop_index('id_traslado', table_name='traslado_interno_detalle')
    op.drop_index('id_producto', table_name='traslado_interno_detalle')
    op.drop_table('traslado_interno_detalle')
    op.drop_index('uk_producto_almacen', table_name='productos_almacen')
    op.drop_index('idx_pa_producto', table_name='productos_almacen')
    op.drop_index('idx_pa_almacen', table_name='productos_almacen')
    op.drop_table('productos_almacen')
    op.drop_index('id_producto', table_name='pedido_proveedor_detalle')
    op.drop_index('id_pedido_proveedor', table_name='pedido_proveedor_detalle')
    op.drop_table('pedido_proveedor_detalle')
    op.drop_index('idx_pcd_producto', table_name='pedido_cliente_detalle')
    op.drop_index('idx_pcd_pedido', table_name='pedido_cliente_detalle')
    op.drop_table('pedido_cliente_detalle')
    op.drop_index('idx_md_producto', table_name='movimiento_detalle')
    op.drop_index('idx_md_movimiento', table_name='movimiento_detalle')
    op.drop_index('idx_md_almacen', table_name='movimiento_detalle')
    op.drop_table('movimiento_detalle')
    op.drop_index('idx_gr_vehiculo', table_name='guia_remision')
    op.drop_index('idx_gr_conductor', table_name='guia_remision')
    op.drop_index('id_pedido_cliente', table_name='guia_remision')
    op.drop_table('guia_remision')
    op.drop_index('uk_envio_pedido', table_name='envios')
    op.drop_index('idx_envio_vehiculo', table_name='envios')
    op.drop_index('id_empleado', table_name='envios')
    op.drop_table('envios')
    op.drop_index('id_pedido_proveedor', table_name='devoluciones_proveedores')
    op.drop_table('devoluciones_proveedores')
    op.drop_index('id_pedido_cliente', table_name='devoluciones_clientes')
    op.drop_table('devoluciones_clientes')
    op.drop_index('idx_cd_producto', table_name='compra_detalle')
    op.drop_index('idx_cd_movimiento', table_name='compra_detalle')
    op.drop_index('idx_cd_compra', table_name='compra_detalle')
    op.drop_table('compra_detalle')
    op.drop_index('id_empleado', table_name='traslados_internos')
    op.drop_index('id_almacen_origen', table_name='traslados_internos')
    op.drop_index('id_almacen_destino', table_name='traslados_internos')
    op.drop_table('traslados_internos')
    op.drop_index('idx_pp_proveedor', table_name='pedidos_proveedores')
    op.drop_index('idx_pp_empleado', table_name='pedidos_proveedores')
    op.drop_index('id_almacen', table_name='pedidos_proveedores')
    op.drop_table('pedidos_proveedores')
    op.drop_index('idx_pc_empleado', table_name='pedidos_clientes')
    op.drop_index('idx_pc_cliente', table_name='pedidos_clientes')
    op.drop_index('idx_pc_almacen', table_name='pedidos_clientes')
    op.drop_table('pedidos_clientes')
    op.drop_index('id_vehiculo', table_name='mantenimiento_vehiculo')
    op.drop_table('mantenimiento_vehiculo')
    op.drop_index('idx_compra_proveedor', table_name='compras')
    op.drop_index('idx_compra_empleado', table_name='compras')
    op.drop_index('idx_compra_almacen', table_name='compras')
    op.drop_table('compras')
    op.drop_index('uk_rol_permiso', table_name='rol_permiso')
    op.drop_index('id_permiso', table_name='rol_permiso')
    op.drop_table('rol_permiso')
    op.drop_index('idx_movimiento_usuario', table_name='movimiento')
    op.drop_index('idx_movimiento_fecha', table_name='movimiento')
    op.drop_table('movimiento')
    op.drop_index('uk_empleado_rol', table_name='empleado_rol')
    op.drop_index('id_rol', table_name='empleado_rol')
    op.drop_table('empleado_rol')
    op.drop_table('conductores')
    op.drop_index('idx_auditoria_usuario', table_name='auditoria')
    op.drop_index('idx_auditoria_fecha', table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_table('ruta')
    op.drop_index('nombre', table_name='roles')
    op.drop_table('roles')
    op.drop_table('restauraciones')
    op.drop_index('nombre', table_name='permisos')
    op.drop_table('permisos')
    op.drop_index('clave', table_name='configuracion')
    op.drop_table('configuracion')
    op.drop_table('backups')
    # ### end Alembic commands ###
